spring:
  application:
    name: pourrfot-cas
  redis:
    host: localhost
    password: 123456
  datasource:
    url: "jdbc:mysql://localhost/pourrfot"
    username: pourrfot
    password: 123456
cas:
  jwk:
    expire: 86400
    keypair: |
      {
          "p": "zX_W7-0SHlPd5mnUqzmV-WkwpkhvSvnMwlG6BWF2K0Gy3ueELjaCP_IIWiXHQdGfQPyyDqoIB5Sx7WalWsVBre23U2w6RYjvltrmwcpGAeMbeW6fWY-ZXzWzpb3wwRZwZQzhMB0KgTIMXjV1ANVO8eLS1GqAHFQ0kYZNCFcKUmk",
          "kty": "RSA",
          "q": "qmNTjkT5Tdogqy8oioX8pSB0viL30yPK1jIFWQPcaqUtUvZHklw1-4RDE8wRlGFK2SZfxJ4AAXWzqa0Y_2oLYv9VEwv0ddbwmEZ_5D2LoCJRCkh9p00VUZInklOKfCj9jvtj6QrlfB0V-c_Ng1fnAKT81N80enY45ABjVJIBm6U",
          "d": "V4OnkjQwH6vDXZCY1Go3vf9OjpF13k_Sjkzl4jky4AyPQ78s5jMN7MAe7Z2usD0hf2FFjh2ezBHocfJS_mB9NdcMbTZtmdv1ogBg0rykXBKml1LXxRvP02IsF4yPY0zeBJmOtwVwKsZzrDWOwFL0_274gOTX-_cZbqcnT3ECYJng8Ya8-a6X9XqXAjve1kr3A4TVe1BMcH1JpgDQMV3HRifNt5ZiZc94rsX0GVPHf-qyFs-9XxfMXDe8NoQiyBtaFRntlGnBjSrRNFQbUs1uCm0jHIac2cU4s3sRXNHK8-pjPjepQVPXb0WK4X42Rg0KYIWSRyarN1oq4X0tK_u6IQ",
          "e": "AQAB",
          "use": "sig",
          "kid": "pourrfot-cas",
          "qi": "MgExJ3fGnl8pjNcRJtA1499SxbcgeyOy4J4K-Vpm1YgDokJTLN8zgrNCTU7VO3-VWuRt9C7vgYcdDNSeuAEISrOS8Tsx5xRssQ4sz354OaDVmdJJuw5OyguFCtOXSa8LR1uNtoUmushFp_8OD_FDc1L_6ECfwd6b8Obg2UQ9E1s",
          "dp": "aaLSwWjzjGV-RwiWCyLCBoDdQk0v8LGyYR2T61orXZcbNNx8JSleETMAuh57bEkufUCo40Lid8snH6tJSvzlg1wUhiy3U7FNwBVs06eAD05IfEayYV6g78FyRLv7-7XmNvvE8m-rS7iHhRIjwDbmqw73Y7wPeQCMOVZ5WNUteCk",
          "alg": "RS256",
          "dq": "Ki2CPoKGcCYh1h5LW9cFDl81ZufDDyoaCOHC_yD8jA2tZY7_cpSO7F72N81ZQLDA1XYxWLt_5tybB9KIkJlQjkYEaj2YWx9E2X0CJZ6ylIZKJ1CAgkyLjXCviQJTEp8W_TDvr316Bzov-XHePrggv8EXsR47oGDpfk82R3YJHd0",
          "n": "iMagPhktzgYivtRCn6nruHfhdk725WYTDFv3bFoEu51dIh-XUfvDjz3JWL1UU9tbN7NNgtrq92ojXxC3DlAho_NjhNGpfoXhCQqiQK9g1d0PJXNZFvIwrRm6sdFKWgaKVeT5pfPYnKtxVKpMT73OQk_jrA118m3cinCmGHuf6uJS9GkdYRSxn8z2cdS_IS8amyE5wkTo8jCyfKsoBqV9K5HGjKSgFviRzNe6J6Sxa6-S30K3ECpwi2O00nWFj-ahwdG0f89JWGStNIq-wuFF3A0x1uHE4gsBvKocEGbadIt9dxMdFNkIh9-o_Cbabeg3H5Shi4waYjY8IZKRjfWwrQ"
      }
  redis:
    key: pourrfot
server:
  servlet:
    context-path: /cas/api
  port: 9001
