###
GET http://localhost:9001/cas/api/jwt/public-key
Accept: application/json


###
GET http://localhost:9001/cas/api/jwt/payload?token=eyJhbGciOiJSUzI1NiIsImtpZCI6InBvdXJyZm90LWNhcyJ9.eyJpZCI6MSwiY3JlYXRlVGltZSI6IjIwMjEtMDQtMThUMTY6MjA6MDkuMDAwKzAwOjAwIiwidXBkYXRlVGltZSI6IjIwMjEtMDQtMThUMTY6MjA6MDkuMDAwKzAwOjAwIiwidXNlcm5hbWUiOiJzcGVuY2VyY2poIiwibmlja25hbWUiOiLolKHkvbPmmIoiLCJwcm9maWxlUGhvdG8iOiIiLCJiaXJ0aCI6IjE5OTgtMDMtMjRUMTY6MDA6MDAuMDAwKzAwOjAwIiwic2V4IjoibWFsZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoic2hvdXNwZW5jZXJjamhAZm94bWFpbC5jb20iLCJ0ZWxlcGhvbmUiOiIxNTAwMDEzMTk2NSIsInBhc3N3b3JkIjoiKioqKioqIiwiZXhwIjoxNjE4ODUwNjczfQ.JgP5CUyw2cr7vrXVf6SKPitOL8L6jr520Wcpi70n9UkHX9QLDc_z4iZETi3Enx_rs4BCfZGZpTT3frJNwB2_2TO-JaTLurieBK6i9W4jYIgzyDPjYyqH4mg7AMow94AA_xsQK1mEH2s6xwRPEgMnBz5_-Wgk36lIcgtHWXIDi3QLiMVeeOhnnHiPiibVrfPJa2d6ByEfS1_yUuSMfw1CfRl56r_jOBUiTtVprDzv9qMiBcPoHv3mkuPem1-jSQYE4dR8FoOSykBELwMDxePqtL9dUw6bS8Tm_lZk_jdcxGdo3lAy6MI71X79cH1cIGCLXVc1EcBDJw4IANPtsso7vg
Content-Type: application/json
