###
POST http://localhost:9001/cas/api/oauth/code
Content-Type: application/json

{
    "clientId": "pourrfot-web",
    "password": "123456",
    "redirectUrl": "http://pourrfot-server.com/api",
    "responseType": "code",
    "scope": "student",
    "state": "state",
    "username": "spencercjh"
}

###
POST http://localhost:9001/cas/api/oauth/token
Accept: application/json
Content-Type: application/json

{
    "code": "555f7174b22a425bbd631f16a1854bf7",
    "state": "state",
    "clientId": "pourrfot-web",
    "clientSecret": "123456",
    "grantType": "AUTHORIZATION_CODE"
}
