###
POST http://localhost:9001/cas/api/oauth/code
Content-Type: application/json

{
    "clientId": "clientId",
    "password": "123456",
    "redirectUrl": "http://localhost:9000/api",
    "responseType": "code",
    "scope": "student",
    "state": "state",
    "username": "spencercjh"
}

###
POST http://localhost:9001/cas/api/oauth/token
Accept: application/json
Content-Type: application/json

{
    "code": "f35baa6b24e949bd8e5610b7ae9e63c1",
    "state": "state",
    "clientId": "clientId",
    "clientSecret": "clientSecret",
    "grantType": "AUTHORIZATION_CODE"
}
